spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}
  swagger-ui:
    enabled: ${ENABLE_SWAGGER:true}
